spring:
  datasource:
    url: jdbc:sqlserver://crud-server1.database.windows.net:1433;database=crud-db;user=shahzebdb@crud-server1;password=password@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    #database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081
